name: Rebuild yklcs.com

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  yklcs-rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger rebuild
        if: always()
        uses: actions/github-script@v7
        id: trigger-rebuild
        env:
          REPO: "yklcs.com"
        with:
          script: |
            await github.rest.repos.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: process.env.REPO,
              workflow_id: build-and-deploy
            })
